name: Ubuntu
on: [push]
jobs:
  Ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - name: Display Run Parameters
      run: |
        echo "::group::User Environment Variables"
        echo "Manifest URL: ${{ github.event.inputs.MANIFEST_URL }}"
        echo "Manifest Branch: ${{ github.event.inputs.MANIFEST_BRANCH }}"
        echo "Device Tree URL: ${{ github.event.inputs.DEVICE_TREE_URL }}"
        echo "Device Tree Branch: ${{ github.event.inputs.DEVICE_TREE_BRANCH }}"
        echo "Device Path: ${{ github.event.inputs.DEVICE_PATH }}"
        echo "Device Name: ${{ github.event.inputs.DEVICE_NAME }}"
        echo "Makefile Name: ${{ github.event.inputs.MAKEFILE_NAME }}"
        echo "Build Target: ${{ github.event.inputs.BUILD_TARGET }}.img"
        echo "::endgroup::"
    
    - name: Install OpenJDK
      run: |
        sudo mkdir /usr/java
        cd /usr/java
        pwd
        sudo wget https://repo.huaweicloud.com/java/jdk/6u45-b06/jdk-6u45-linux-x64.bin
        sudo chmod 777 jdk-6u45-linux-x64.bin
        sudo sh -c './jdk-6u45-linux-x64.bin'
        sudo sh -c 'echo "export JAVA_HOME=/usr/java/jdk1.6.0_45" >> /etc/profile'
        sudo sh -c 'echo "export JAVA_BIN=/usr/java/jdk1.6.0_45/bin" >> /etc/profile'
        sudo sh -c 'echo "export PATH=$PATH:$JAVA_HOME/bin" >> /etc/profile'
        sudo sh -c 'echo "export CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar" >> /etc/profile'
        sudo sh -c 'echo "export JAVA_HOME JAVA_BIN PATH CLASSPATH" >> /etc/profile'
        echo "rm java"
        sudo rm /usr/bin/java
        echo "set java"
        sudo -s
        sudo sh -c 'source /etc/profile'
        echo "okey"
        cd /home/runner/work/Action-TWRP-Builder/Action-TWRP-Builder
        java -version
        echo "end"
