name: Ubuntu
on: [push]
jobs:
  Ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - name: Display Run Parameters
      run: |
        echo "::group::User Environment Variables"
        echo "Manifest URL: ${{ github.event.inputs.MANIFEST_URL }}"
        echo "Manifest Branch: ${{ github.event.inputs.MANIFEST_BRANCH }}"
        echo "Device Tree URL: ${{ github.event.inputs.DEVICE_TREE_URL }}"
        echo "Device Tree Branch: ${{ github.event.inputs.DEVICE_TREE_BRANCH }}"
        echo "Device Path: ${{ github.event.inputs.DEVICE_PATH }}"
        echo "Device Name: ${{ github.event.inputs.DEVICE_NAME }}"
        echo "Makefile Name: ${{ github.event.inputs.MAKEFILE_NAME }}"
        echo "Build Target: ${{ github.event.inputs.BUILD_TARGET }}.img"
        echo "::endgroup::"
    
    - name: Install OpenJDK
      run: |
        sudo mkdir /usr/lib/java
        cd /usr/lib/java
        pwd
        sudo wget https://repo.huaweicloud.com/java/jdk/6u45-b06/jdk-6u45-linux-x64.bin
        sudo chmod 777 jdk-6u45-linux-x64.bin
        sudo sh -c './jdk-6u45-linux-x64.bin'
        echo "set java file"
        sudo update-alternatives --install "/usr/bin/java" "java" "/usr/lib/java/jdk1.6.0_45/bin/java" 1
        sudo update-alternatives --install "/usr/bin/javac" "javac" "/usr/lib/java/jdk1.6.0_45/bin/javac" 1
        sudo update-alternatives --install "/usr/bin/javaws" "javaws" "/usr/lib/java/jdk1.6.0_45/bin/javaws" 1
        echo "set java"
        sudo sh -c 'echo "export JAVA_HOME=/usr/lib/java/jdk1.6.0_45" >> ~/.bashrc'
        sudo sh -c 'echo "export PATH="$PATH:$JAVA_HOME/bin" >> ~/.bashrc'
        echo "okey"
        cd /home/runner/work/Action-TWRP-Builder/Action-TWRP-Builder
        java -version
        echo "end"
